name: kapital_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  material_design_icons_flutter: ^7.0.7296
  sync_http: ^0.3.1
  flutter_native_splash: ^2.4.6
  device_preview: ^1.2.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^7.1.0

flutter_native_splash:
  android_12: 
    image: "assets/img/IconKitchen-Output/android/res/mipmap-mdpi/ic_launcher_background.png"
  icon_background_color: "#000000"
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "assets/img/IconKitchen-Output/android/res/mipmap-xxxhdpi/ic_launcher_monochrome.png"

flutter_icons:
    android: true
    ios: true
    image_path: "assets/img/IconKitchen-Output/ios/AppIcon-40@3x.png"
    remove_alpha_ios: true
    adaptive_icon_background: "assets/img/IconKitchen-Output/android/res/mipmap-xxxhdpi/ic_launcher_background.png"
    adaptive_icon_foreground: "assets/img/IconKitchen-Output/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
    adaptive_icon_monochrome: "assets/img/IconKitchen-Output/android/res/mipmap-xxxhdpi/ic_launcher_monochrome.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
      - family: InterBlack
        fonts:
          - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
      - family: Lobster
        fonts:
          - asset: assets/fonts/Lobster/Lobster-Regular.ttf
      - family: Marvel
        fonts:
          - asset: assets/fonts/Marvel/Marvel-Regular.ttf