// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YbbpzufP1G4wVS9Uji2cMIz3KOWlHcI',
    appId: '1:342870434502:web:661708a0585c93fd94adc7',
    messagingSenderId: '342870434502',
    projectId: 'kapital5-6',
    authDomain: 'kapital5-6.firebaseapp.com',
    storageBucket: 'kapital5-6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_bKMz195r1N86jpAo2zx_PDfdk_dt3w',
    appId: '1:342870434502:android:a9bca5490c94b5e594adc7',
    messagingSenderId: '342870434502',
    projectId: 'kapital5-6',
    storageBucket: 'kapital5-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Wha0EhA7oXf-A-G5j73Q-l8Kfs_piwc',
    appId: '1:342870434502:ios:abb3960d2b2142c194adc7',
    messagingSenderId: '342870434502',
    projectId: 'kapital5-6',
    storageBucket: 'kapital5-6.firebasestorage.app',
    iosBundleId: 'com.example.kapital5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Wha0EhA7oXf-A-G5j73Q-l8Kfs_piwc',
    appId: '1:342870434502:ios:abb3960d2b2142c194adc7',
    messagingSenderId: '342870434502',
    projectId: 'kapital5-6',
    storageBucket: 'kapital5-6.firebasestorage.app',
    iosBundleId: 'com.example.kapital5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YbbpzufP1G4wVS9Uji2cMIz3KOWlHcI',
    appId: '1:342870434502:web:4a6130adab5f932794adc7',
    messagingSenderId: '342870434502',
    projectId: 'kapital5-6',
    authDomain: 'kapital5-6.firebaseapp.com',
    storageBucket: 'kapital5-6.firebasestorage.app',
  );
}
